#!/usr/bin/env npx tsx
/**
 * Generate ccadbStatic.ts from Mozilla CCADB
 *
 * This script fetches certificate data from the Mozilla certifi package (Python's
 * standard CA bundle which is based on Mozilla CCADB), and generates a TypeScript
 * file with base64-encoded certificates.
 * It also runs eslint --fix on the generated file.
 */

import { PEM, X509 } from '@hazae41/x509';
import fs from 'fs/promises';
import path from 'path';
import { execSync } from 'child_process';

interface CertRow {
  PEM: string;
}

async function fetchCertificatesFromMozilla(): Promise<CertRow[]> {
  // Fetch from certifi (Python's Mozilla CA bundle)
  // This is the most reliable and regularly updated source
  const url =
    'https://raw.githubusercontent.com/certifi/python-certifi/master/certifi/cacert.pem';
  console.log('Fetching certificates from Mozilla CCADB (via certifi)...');

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(
      `Failed to fetch certificates: ${response.status} ${response.statusText}`
    );
  }

  const pem = await response.text();
  const certRows: CertRow[] = [];

  // Extract certificates from the PEM bundle
  // Match complete certificate blocks (from BEGIN to END)
  const certRegex =
    /-----BEGIN CERTIFICATE-----[\s\S]*?-----END CERTIFICATE-----/g;
  const matches = pem.match(certRegex);

  if (matches) {
    for (const cert of matches) {
      certRows.push({ PEM: cert.trim() });
    }
  }

  return certRows;
}

async function generateCCADB() {
  const certRows = await fetchCertificatesFromMozilla();

  const base64Certs: string[] = [];
  const seenSubjects = new Set<string>();
  let skipped = 0;

  for (const cert of certRows) {
    try {
      const pem = PEM.decodeOrThrow(cert.PEM);
      const x509 = X509.readAndResolveFromBytesOrThrow(X509.Certificate, pem);

      const x501 = x509.tbsCertificate.subject.toX501OrThrow();

      // Check for duplicates
      if (seenSubjects.has(x501)) {
        skipped++;
        continue;
      }
      seenSubjects.add(x501);

      // Convert PEM to base64
      const certBase16 = Buffer.from(pem).toString('hex');
      const certBase64 = Buffer.from(Buffer.from(certBase16, 'hex')).toString(
        'base64'
      );

      base64Certs.push(certBase64);
    } catch {
      skipped++;
    }
  }

  // Generate ccadbStatic.ts with base64 certificates
  const staticOutputPath = path.join(
    process.cwd(),
    'src/cadenas/mods/ccadb/ccadbStatic.ts'
  );
  const staticOutput =
    '// Auto-generated by scripts/generate-ccadb.ts\n' +
    '// Base64-encoded X.509 DER certificates from Mozilla CCADB\n' +
    '\n' +
    'export const ccadbStaticBase64: readonly string[] = ' +
    JSON.stringify(base64Certs) +
    ';\n';
  await fs.writeFile(staticOutputPath, staticOutput, 'utf8');

  // Run eslint --fix on generated file
  try {
    console.log(`Running eslint --fix on ${staticOutputPath}...`);
    execSync(`eslint --fix "${staticOutputPath}"`, { stdio: 'inherit' });
  } catch (error) {
    console.warn(`⚠️  eslint --fix failed:`, error);
  }

  const total = base64Certs.length;
  console.log(`✅ Generated ${staticOutputPath}`);
  console.log(`📊 ${total} certificates included, ${skipped} skipped`);
}

generateCCADB().catch(error => {
  console.error('❌ Error:', error.message);
  process.exit(1);
});
