// Auto-generated by scripts/generate-ccadb.ts --source=curl
// SPKI hashes for certificate validation (used by ccadbDynamic.ts)

export const certHashes: string[] = [
  // AffirmTrust Premium ECC (issued by AffirmTrust Premium ECC)
  // Expires: 2040-12-31T14:20:24.000Z
  '3219b09114ff495a3eb6eb00c2efeab34002ae5f0a56c7679ea087a3fa037e4f',

  // GlobalSign (issued by GlobalSign)
  // Expires: 2038-01-19T03:14:07.000Z
  '08b3a6335fce5ef48f8f0e543986c07fd18a3b1226129f61864bbd5bdd1f1cc9',

  // Amazon Root CA 4 (issued by Amazon Root CA 4)
  // Expires: 2040-05-26T00:00:00.000Z
  'f7ecded5c66047d28ed6466b543c40e0743abe81d109254dcf845d4c2c7853c5',

  // Certainly Root E1 (issued by Certainly Root E1)
  // Expires: 2046-04-01T00:00:00.000Z
  '1ef64625daa2e5d433d7449ae31a200d1025e0012a8fecfa70932f8b599b75dd',

  // Amazon Root CA 3 (issued by Amazon Root CA 3)
  // Expires: 2040-05-26T00:00:00.000Z
  '36abc32656acfc645c61b71613c4bf21c787f5cabbee48348d58597803d7abc9',

  // Entrust Root Certification Authority - EC1 (issued by Entrust Root Certification Authority - EC1)
  // Expires: 2037-12-18T15:55:36.000Z
  'fea2b7d645fba73d753c1ec9a7870c40e1f7b0c561e927b985bf711866e36f22',

  // D-TRUST EV Root CA 1 2020 (issued by D-TRUST EV Root CA 1 2020)
  // Expires: 2035-02-11T09:59:59.000Z
  '9d37e4a989eab3882d116052fc8b58446702cb593726e4604c3795940c7103e2',

  // D-TRUST BR Root CA 1 2020 (issued by D-TRUST BR Root CA 1 2020)
  // Expires: 2035-02-11T09:44:59.000Z
  '603f76f28c9feba83ec751edb66c8d7523ea40fe49fe74427629f50dabbcf55a',

  // GTS Root R3 (issued by GTS Root R3)
  // Expires: 2036-06-22T00:00:00.000Z
  '4179edd981ef747477b49626408af43daa2ca7ab7f9e082c1060f84096774348',

  // GTS Root R4 (issued by GTS Root R4)
  // Expires: 2036-06-22T00:00:00.000Z
  '9847e5653e5e9e847516e5cb818606aa7544a19be67fd7366d506988e8d84347',

  // GlobalSign Root E46 (issued by GlobalSign Root E46)
  // Expires: 2046-03-20T00:00:00.000Z
  'e04a022ce32f4ccf2c7f6046287b828a32a909f5e751447f83fd2c71f6fd8173',

  // vTrus ECC Root CA (issued by vTrus ECC Root CA)
  // Expires: 2043-07-31T07:26:44.000Z
  'a246b822f96cfecc155156e5476957845492acf32187ec8a2ef12d89618d711d',

  // Atos TrustedRoot Root CA ECC TLS 2021 (issued by Atos TrustedRoot Root CA ECC TLS 2021)
  // Expires: 2041-04-17T09:26:22.000Z
  '608963c78c455e6e34b072468ace0956cff18d34643f9f305b7162fa181979fc',

  // DigiCert TLS ECC P384 Root G5 (issued by DigiCert TLS ECC P384 Root G5)
  // Expires: 2046-01-14T23:59:59.000Z
  'a02fafa192c8cb81cb1341554f9c05b71cca2a890b0d1298d683647c961efbdf',

  // ISRG Root X2 (issued by ISRG Root X2)
  // Expires: 2040-09-17T16:00:00.000Z
  '762195c225586ee6c0237456e2107dc54f1efc21f61a792ebd515913cce68332',

  // GlobalSign (issued by GlobalSign)
  // Expires: 2038-01-19T03:14:07.000Z
  '7e0ead76bb6819dc2f54511a84354f6e8b307b9dd82058ea6c004f01d9dda5df',

  // SecureSign Root CA15 (issued by SecureSign Root CA15)
  // Expires: 2045-04-08T08:32:56.000Z
  'f0011f92fcf9be36c7a5b36e7bc862ab20e94ef36fea8a561db0a8d7750c1f51',

  // BJCA Global Root CA2 (issued by BJCA Global Root CA2)
  // Expires: 2044-12-12T03:18:21.000Z
  'cc94a5a0319ff77a4ccadd821c4c59674e44d52816cbd1dfe2c761370ad4d21c',

  // emSign ECC Root CA - C3 (issued by emSign ECC Root CA - C3)
  // Expires: 2043-02-18T18:30:00.000Z
  'eabc185c4e82d942b1a5978ba3c0181487d6b3b9974e5c49f72f6d0bd9637150',

  // TrustAsia TLS ECC Root CA (issued by TrustAsia TLS ECC Root CA)
  // Expires: 2044-05-15T05:41:55.000Z
  'f4632e58701c0bd7dafc7e3831355ec433fc13777de286683e8ec50964df0452',

  // OISTE Server Root ECC G1 (issued by OISTE Server Root ECC G1)
  // Expires: 2048-05-24T14:42:27.000Z
  'd439dd80f1e3bc5c9e5f13e8bff7a8887df9dc1c3e19d76af70c8f8d985eef22',

  // Security Communication ECC RootCA1 (issued by Security Communication ECC RootCA1)
  // Expires: 2038-01-18T05:15:28.000Z
  '3329bfa13b6007ab5fc3713f0acb289426e2fbc99cc5c110a914b139571600b6',

  // SSL.com TLS ECC Root CA 2022 (issued by SSL.com TLS ECC Root CA 2022)
  // Expires: 2046-08-19T16:33:47.000Z
  '1bf00d5c8f13c094dd17e00504cf0888850f12fd067fa1f92c0fdbf60b86e321',

  // Sectigo Public Server Authentication Root E46 (issued by Sectigo Public Server Authentication Root E46)
  // Expires: 2046-03-21T23:59:59.000Z
  'b0b56335468561f5bb9fa12d801784a633a572705d34f32b643445dfa8b005d1',

  // DigiCert Global Root G3 (issued by DigiCert Global Root G3)
  // Expires: 2038-01-15T12:00:00.000Z
  'b94c198300cec5c057ad0727b70bbe91816992256439a7b32f4598119dda9c97',

  // e-Szigno Root CA 2017 (issued by e-Szigno Root CA 2017)
  // Expires: 2042-08-22T12:07:06.000Z
  '42431627ea76cc78697f915e3455b1b2ec82ff2f6380ee6423ef3c0840b7e631',

  // Telekom Security TLS ECC Root 2020 (issued by Telekom Security TLS ECC Root 2020)
  // Expires: 2045-08-25T23:59:59.000Z
  'eab0de5a46419010b01b2d55553fc111aa82b43d9395edfeaeaa8c76e6ad1995',

  // DigiCert Assured ID Root G3 (issued by DigiCert Assured ID Root G3)
  // Expires: 2038-01-15T12:00:00.000Z
  '15eed339594b304f8cf847b477371d8d6fec61f4db2b01af589e7c53b35cae4c',

  // emSign ECC Root CA - G3 (issued by emSign ECC Root CA - G3)
  // Expires: 2043-02-18T18:30:00.000Z
  '8d417db2dd8bf5e3084d1e3f196d583849d81bdd4c00c70b9d39369e96b8c782',

  // HARICA TLS ECC Root CA 2021 (issued by HARICA TLS ECC Root CA 2021)
  // Expires: 2045-02-13T11:01:09.000Z
  'fc784300ec8df4d3d1bad763835182918d52a9ff0238bdf695a1cd9bdb98321c',

  // TrustAsia Global Root CA G4 (issued by TrustAsia Global Root CA G4)
  // Expires: 2046-05-19T02:10:22.000Z
  '07a2904d4bff9604ea1331ae990e9ffe331232e69ecb8a08cd49d8e34757db41',

  // Microsoft ECC Root Certificate Authority 2017 (issued by Microsoft ECC Root Certificate Authority 2017)
  // Expires: 2042-07-18T23:16:04.000Z
  '35f53ce1264611e03340fe37e1ec7d4cc986c5613dca70fd04aa44545f2daf28',

  // Trustwave Global ECC P256 Certification Authority (issued by Trustwave Global ECC P256 Certification Authority)
  // Expires: 2042-08-23T19:35:10.000Z
  '497128fc90656b87290482b223efb72240fe9c421e79938de5f8110cb0be9056',

  // Certum EC-384 CA (issued by Certum EC-384 CA)
  // Expires: 2043-03-26T07:24:54.000Z
  'de7b6932e9c44582ce0de07abdab7eea90c75d6d2a07331df57bd5cb88553d13',

  // OISTE WISeKey Global Root GC CA (issued by OISTE WISeKey Global Root GC CA)
  // Expires: 2042-05-09T09:58:33.000Z
  'fd371bea9755ff60c8828c849b8e5215de532d61b009855fa0ad630d90eef82e',

  // AC RAIZ FNMT-RCM SERVIDORES SEGUROS (issued by AC RAIZ FNMT-RCM SERVIDORES SEGUROS)
  // Expires: 2043-12-20T09:37:33.000Z
  '453b74809b69019627f2f843001db5950cdd1d45371053e7f3dfdbc3714113c6',

  // FIRMAPROFESIONAL CA ROOT-A WEB (issued by FIRMAPROFESIONAL CA ROOT-A WEB)
  // Expires: 2047-03-31T09:01:36.000Z
  '2db2ae4d0d08a4dc7b7a5c911b36b42e3068d2e58657efa61a2f2f69c553b858',

  // COMODO ECC Certification Authority (issued by COMODO ECC Certification Authority)
  // Expires: 2038-01-18T23:59:59.000Z
  'e7ca91bbfbb18788057b3a8070446ea5291160194102f7dcc3b9848c63cb9cd5',

  // SSL.com Root Certification Authority ECC (issued by SSL.com Root Certification Authority ECC)
  // Expires: 2041-02-12T18:14:03.000Z
  'a320f4d534d7be97c1ae8dd0499735bc895c323add2d388bfccf662c23d7f99a',

  // USERTrust ECC Certification Authority (issued by USERTrust ECC Certification Authority)
  // Expires: 2038-01-18T23:59:59.000Z
  '2021917e98263945c859c43f1d73cb4139053c414fa03ca3bc7ee88614298f3b',

  // SSL.com EV Root Certification Authority ECC (issued by SSL.com EV Root Certification Authority ECC)
  // Expires: 2041-02-12T18:15:23.000Z
  '348767cdad3bdd28b2b8dd5351aec30c68cec5cd69d276df3827dbc4f5806464',

  // Trustwave Global ECC P384 Certification Authority (issued by Trustwave Global ECC P384 Certification Authority)
  // Expires: 2042-08-23T19:36:43.000Z
  '828b0eeff24654e8ff5841a29dd5d4e3ed30952ca43425a79283407208d39d16',

  // Hellenic Academic and Research Institutions ECC RootCA 2015 (issued by Hellenic Academic and Research Institutions ECC RootCA 2015)
  // Expires: 2040-06-30T10:37:12.000Z
  'bb52086d0639e8db332775ac8f4e8435d92ceb00f4e24f28fc0eabe240772e80',

  // Starfield Root Certificate Authority - G2 (issued by Starfield Root Certificate Authority - G2)
  // Expires: 2037-12-31T23:59:59.000Z
  '808d68b3fab4884a5f971ace7d10550d7a95a163774f3ec36afffb213fbe4c74',

  // Starfield Services Root Certificate Authority - G2 (issued by Starfield Services Root Certificate Authority - G2)
  // Expires: 2037-12-31T23:59:59.000Z
  '2b071c59a0a0ae76b0eadb2bad23bad4580b69c3601b630c2eaf0613afa83f92',

  // OU=certSIGN ROOT CA (issued by OU=certSIGN ROOT CA)
  // Expires: 2031-07-04T17:20:04.000Z
  'dbc1e3a15238a0483bcdb8fdec616e03e705a48e2a501157cadf3b9c7311c5e5',

  // Amazon Root CA 1 (issued by Amazon Root CA 1)
  // Expires: 2038-01-17T00:00:00.000Z
  'fbe3018031f9586bcbf41727e417b7d1c45c2f47f93be372a17b96b50757d5a2',

  // AffirmTrust Commercial (issued by AffirmTrust Commercial)
  // Expires: 2030-12-31T14:06:06.000Z
  '6c464b9a5b233a5e874da765c26f045010d2ddcff45794f0b4c7e4aafa501495',

  // AffirmTrust Networking (issued by AffirmTrust Networking)
  // Expires: 2030-12-31T14:08:24.000Z
  '94072ad3f58f70f93098e5a5f6c04c96c710bd849d83184919ae90eb890ae400',

  // GlobalSign (issued by GlobalSign)
  // Expires: 2029-03-18T10:00:00.000Z
  '706bb1017c855c59169bad5c1781cf597f12d2cad2f63d1a4aa37493800ffb80',

  // SZAFIR ROOT CA2 (issued by SZAFIR ROOT CA2)
  // Expires: 2035-10-19T07:43:30.000Z
  '6e364b6133deefdcbb21273c5f445a20afbc05038d5b021c0c2153039016345b',

  // SecureSign Root CA12 (issued by SecureSign Root CA12)
  // Expires: 2040-04-08T05:36:46.000Z
  'e14e51891f3492243eea613bc2c814d47224b224c57d38169e958e30b3dedee4',

  // emSign Root CA - C1 (issued by emSign Root CA - C1)
  // Expires: 2043-02-18T18:30:00.000Z
  'b7408b4d2be0238ba37004dd34e276c6019bd2f24c9db7d4980f5f6c359a4bcc',

  // OU=Security Communication RootCA2 (issued by OU=Security Communication RootCA2)
  // Expires: 2029-05-29T05:00:39.000Z
  '3380709af3b096be3cc2a40548142c0a520028db09e2cb77ae2206616ab6cbb4',

  // Atos TrustedRoot 2011 (issued by Atos TrustedRoot 2011)
  // Expires: 2030-12-31T23:59:59.000Z
  'e5ca37bc7b6c361979bc6b123ca9a1db019046d7ff5f57dfb854b19d10b0682f',

  // TWCA Root Certification Authority (issued by TWCA Root Certification Authority)
  // Expires: 2030-12-31T15:59:59.000Z
  '92c46879626ef2cc1ecea50c72fb5e385844095f21cbf3b283cb82e6b9fc6a58',

  // DigiCert Global Root G2 (issued by DigiCert Global Root G2)
  // Expires: 2038-01-15T12:00:00.000Z
  '8bb593a93be1d0e8a822bb887c547890c3e706aad2dab76254f97fb36b82fc26',

  // emSign Root CA - G1 (issued by emSign Root CA - G1)
  // Expires: 2043-02-18T18:30:00.000Z
  '376a1a7082a593dccc20d561d119e9ab8d30f11cc321d0a37fa41f0df284e01c',

  // DigiCert Assured ID Root G2 (issued by DigiCert Assured ID Root G2)
  // Expires: 2038-01-15T12:00:00.000Z
  'f1c6ba670cfc88e4df52973cae420f0a089dd474144fe5806c420064e1591229',

  // Certigna (issued by Certigna)
  // Expires: 2027-06-29T15:13:05.000Z
  '510d20e5c47f63cf666b20f61af62bc099a42ac824ffa443a2da7c90b1808a91',

  // DigiCert Global Root CA (issued by DigiCert Global Root CA)
  // Expires: 2031-11-10T00:00:00.000Z
  'aff988906dde12955d9bebbf928fdcc31cce328d5b9384f21c8941ca26e20391',

  // OISTE WISeKey Global Root GB CA (issued by OISTE WISeKey Global Root GB CA)
  // Expires: 2039-12-01T15:10:31.000Z
  '149f2ee63b9a5e5803240a770dc991fc2e3445e62831c245a49bc4f1f738ff9c',

  // DigiCert Assured ID Root CA (issued by DigiCert Assured ID Root CA)
  // Expires: 2031-11-10T00:00:00.000Z
  '23f2edff3ede90259a9e30f40af8f912a5e5b3694e6938440341f6060e014ffa',

  // SecureTrust CA (issued by SecureTrust CA)
  // Expires: 2029-12-31T19:40:55.000Z
  '77290717614b25f12964ebdb38b5f83caadc0f6c36b0777f880fc6dee1d339cc',

  // Certum Trusted Network CA (issued by Certum Trusted Network CA)
  // Expires: 2029-12-31T12:07:37.000Z
  'aa2630a7b617b04d0a294bab7a8caaa5016e6dbe604837a83a85719fab667eb5',

  // Secure Global CA (issued by Secure Global CA)
  // Expires: 2029-12-31T19:52:06.000Z
  '2596904dc4d699ae20c2cef4dce47f285937d77464ac370746f52dea76ba0c28',

  // T-TeleSec GlobalRoot Class 2 (issued by T-TeleSec GlobalRoot Class 2)
  // Expires: 2033-10-01T23:59:59.000Z
  '6106c0e3a0a299831875127bd7d3cc1859803d511cac11eb6e0840dd166fc10e',

  // T-TeleSec GlobalRoot Class 3 (issued by T-TeleSec GlobalRoot Class 3)
  // Expires: 2033-10-01T23:59:59.000Z
  '8d767764b3cbda08929d072a22a561f4dcdd1bc57d3cbddc948c47d2b47f9122',

  // Go Daddy Root Certificate Authority - G2 (issued by Go Daddy Root Certificate Authority - G2)
  // Expires: 2037-12-31T23:59:59.000Z
  '2a8f2d8af0eb123898f74c866ac3fa669054e23c17bc7a95bd0234192dc635d0',

  // DigiCert High Assurance EV Root CA (issued by DigiCert High Assurance EV Root CA)
  // Expires: 2031-11-10T00:00:00.000Z
  '5a889647220e54d6bd8a16817224520bb5c78e58984bd570506388b9de0f075f',

  // Microsec e-Szigno Root CA 2009 (issued by Microsec e-Szigno Root CA 2009)
  // Expires: 2029-12-30T11:30:18.000Z
  '616167201433aea6c8e5e3070afcaf6749188f814bd1abb179ae8dad3abf26ec',

  // NetLock Arany (Class Gold) Főtanúsítvány (issued by NetLock Arany (Class Gold) Főtanúsítvány)
  // Expires: 2028-12-06T15:08:21.000Z
  'f48badd7df6a06690d0ae31373b12855f8dedb14517f362a313101cc98cc6b35',

  // COMODO Certification Authority (issued by COMODO Certification Authority)
  // Expires: 2029-12-31T23:59:59.000Z
  '006d7be7555dd82026442c4f1a27a80e89a1989cb87b34448ed2194c18196d5e',

  // D-TRUST Root Class 3 CA 2 2009 (issued by D-TRUST Root Class 3 CA 2 2009)
  // Expires: 2029-11-05T08:35:58.000Z
  'eca0f181402ce7a8652b31b4d036df247e3a30b7f41a50d91ec4f90b006b43a1',

  // Entrust Root Certification Authority - G2 (issued by Entrust Root Certification Authority - G2)
  // Expires: 2030-12-07T17:55:54.000Z
  '76ee8590374c715437bbca6bba6028eadde2dc6dbbb8c3f610e851f11d1ab7f5',

  // D-TRUST Root Class 3 CA 2 EV 2009 (issued by D-TRUST Root Class 3 CA 2 EV 2009)
  // Expires: 2029-11-05T08:50:46.000Z
  'ff342fb6c4c8bd30a4706f73489539f19e6e48cc05f46254654f6610dbc540e9',

  // TUBITAK Kamu SM SSL Kok Sertifikasi - Surum 1 (issued by TUBITAK Kamu SM SSL Kok Sertifikasi - Surum 1)
  // Expires: 2043-10-25T08:25:55.000Z
  '55e00be277ceb0545299f24fd9f877e2acf32852db43ffcd29bca74b39b4c9fa',

  // Entrust Root Certification Authority (issued by Entrust Root Certification Authority)
  // Expires: 2026-11-27T20:53:42.000Z
  '6dbfae00d37b9cd73f8fb47de65917af00e0dddf42dbceac20c17c0275ee2095',

  // Certum Trusted Network CA 2 (issued by Certum Trusted Network CA 2)
  // Expires: 2046-10-06T08:39:56.000Z
  '6b3b57e9ec88d1bb3d01637ff33c7698b3c9758255e9f01ea9178f3e7f3b2b52',

  // COMODO RSA Certification Authority (issued by COMODO RSA Certification Authority)
  // Expires: 2038-01-18T23:59:59.000Z
  '82b5f84daf47a59c7ab521e4982aefa40a53406a3aec26039efa6b2e0e7244c1',

  // Trustwave Global Certification Authority (issued by Trustwave Global Certification Authority)
  // Expires: 2042-08-23T19:34:12.000Z
  '2e06cae1fc20b200e6fb748557a4444bec9317dfff2e4151669e0f7944f0a9e0',

  // SSL.com Root Certification Authority RSA (issued by SSL.com Root Certification Authority RSA)
  // Expires: 2041-02-12T17:39:39.000Z
  'd1c45377ebdcd618cd1651dc2e02c21d751e5aa9fcd1b3431ff6ecf6a31348fa',

  // USERTrust RSA Certification Authority (issued by USERTrust RSA Certification Authority)
  // Expires: 2038-01-18T23:59:59.000Z
  'c784333d20bcd742b9fdc3236f4e509b8937070e73067e254dd3bf9c45bf4dde',

  // SSL.com EV Root Certification Authority RSA R2 (issued by SSL.com EV Root Certification Authority RSA R2)
  // Expires: 2042-05-30T18:14:37.000Z
  '7cd67c248f69d83fc2f9bb01dcb1f7ad67a363d046043796d0984c3a231f6bb0',

  // ANF Secure Server Root CA (issued by ANF Secure Server Root CA)
  // Expires: 2039-08-30T10:00:38.000Z
  '9a52ff6a3cb6e353a08567e0dc9c395b300d60a22292ab8c18c1656b2983ae90',

  // Izenpe.com (issued by Izenpe.com)
  // Expires: 2037-12-13T08:27:25.000Z
  '952c2039c0243eb515dd73d83fc3643184874feb0862a9837731ed9b4742e17a',

  // TeliaSonera Root CA v1 (issued by TeliaSonera Root CA v1)
  // Expires: 2032-10-18T12:00:50.000Z
  '10ba3485ca8bb6880ab9531a4063e4001555561c7f2e055165f49b2d74fc5f6b',

  // TWCA Global Root CA (issued by TWCA Global Root CA)
  // Expires: 2030-12-31T15:59:59.000Z
  'c444b5b66ce5d71e1b5e40f27385c95cbfd24a05b56f70cac0992f0f50c3379c',

  // Amazon Root CA 2 (issued by Amazon Root CA 2)
  // Expires: 2040-05-26T00:00:00.000Z
  '7f4296fc5b6a4e3b35d3c369623e364ab1af381d8fa7121533c9d6c633ea2461',

  // AffirmTrust Premium (issued by AffirmTrust Premium)
  // Expires: 2040-12-31T14:10:36.000Z
  'c7f43b4cf5b71568294f822b53762605f6ddd15cadece739e9e2c3cba61e9d67',

  // UCA Global G2 Root (issued by UCA Global G2 Root)
  // Expires: 2040-12-31T00:00:00.000Z
  '1255cabe8152fa64df942f7a47417e29f96c1ce11bf8c84ecbe2815cc1280810',

  // OU=certSIGN ROOT CA G2 (issued by OU=certSIGN ROOT CA G2)
  // Expires: 2042-02-06T09:27:35.000Z
  'cbad7b1d384849df0946b7ee8e7f5f7ce3aed876fda7bc9d30d8b16f29ff2c53',

  // Certainly Root R1 (issued by Certainly Root R1)
  // Expires: 2046-04-01T00:00:00.000Z
  '3f93f3fcf79d225d213eef6a4a3f5885cf84fe3d7a7a3c11553517688c0e2100',

  // vTrus Root CA (issued by vTrus Root CA)
  // Expires: 2043-07-31T07:24:05.000Z
  'e06647e52610160c3e83c42d22e39aa8750c584d6c24afaed54a61164742000a',

  // GTS Root R1 (issued by GTS Root R1)
  // Expires: 2036-06-22T00:00:00.000Z
  '871a9194f4eed5b312ff40c84c1d524aed2f778bbff25f138cf81f680a7adc67',

  // GTS Root R2 (issued by GTS Root R2)
  // Expires: 2036-06-22T00:00:00.000Z
  '55f77de41c03792428f8d518c55104225be43a5598d926a528ad653e1ccec7bf',

  // Buypass Class 2 Root CA (issued by Buypass Class 2 Root CA)
  // Expires: 2040-10-26T08:38:03.000Z
  '5955ae291574a931342cf7450e16652ede1e0fb3097e1571dfac11c915601564',

  // Buypass Class 3 Root CA (issued by Buypass Class 3 Root CA)
  // Expires: 2040-10-26T08:28:58.000Z
  'b03d87b056d08cc9d4e675ef19ca83ab53532168a8258598be72e6d85c7dd7c1',

  // UCA Extended Validation Root (issued by UCA Extended Validation Root)
  // Expires: 2038-12-31T00:00:00.000Z
  '5c41a73ab2c35dfcd771f6fd6e3e8fac9b469d386cadda56a95b646eb48cca34',

  // GlobalSign Root R46 (issued by GlobalSign Root R46)
  // Expires: 2046-03-20T00:00:00.000Z
  'ae7f962cb9e6a7dbf7b833fb18fa9b71a89175df949c232b6a9ef7cb3df2bbfc',

  // IdenTrust Commercial Root CA 1 (issued by IdenTrust Commercial Root CA 1)
  // Expires: 2034-01-16T18:12:23.000Z
  '07e854f26a7cbd389927aa041bfef1b6cd21dd143818ad947dc655a9e587fe88',

  // QuoVadis Root CA 3 G3 (issued by QuoVadis Root CA 3 G3)
  // Expires: 2042-01-12T20:26:32.000Z
  'f3438e23b3ce532522facf307923f58fd18608e9ba7addc30e952b43c49616c3',

  // QuoVadis Root CA 2 G3 (issued by QuoVadis Root CA 2 G3)
  // Expires: 2042-01-12T18:59:32.000Z
  '4a49edbd2f8f8230bd5592b313573fe1c172a45fa98011cc1eddbb36ade3fce5',

  // QuoVadis Root CA 1 G3 (issued by QuoVadis Root CA 1 G3)
  // Expires: 2042-01-12T17:27:44.000Z
  '86a68f050034126a540d39db2c5f917ef66a94fb9619fa1ecd827cea46ba0cb0',

  // Atos TrustedRoot Root CA RSA TLS 2021 (issued by Atos TrustedRoot Root CA RSA TLS 2021)
  // Expires: 2041-04-17T09:21:09.000Z
  'f7ca77a610e3d42447240692dbd57cfd13cf042acd2062e6a62b87b9ed81c1a7',

  // DigiCert TLS RSA4096 Root G5 (issued by DigiCert TLS RSA4096 Root G5)
  // Expires: 2046-01-14T23:59:59.000Z
  '6a97b51c8219e93e5dec64bad5806cdeb0f8355be47e757010b702456e01aafd',

  // IdenTrust Public Sector Root CA 1 (issued by IdenTrust Public Sector Root CA 1)
  // Expires: 2034-01-16T17:53:32.000Z
  '58dd61feb36ea7d258724371709149cb121337864cacb2d0999ad20739d06477',

  // CA Disig Root R2 (issued by CA Disig Root R2)
  // Expires: 2042-07-19T09:15:30.000Z
  '702116ccd8bf23e16466f0e0dba0ed6a239a9c1cd6a8f5a66b39af3595020385',

  // HiPKI Root CA - G1 (issued by HiPKI Root CA - G1)
  // Expires: 2037-12-31T15:59:59.000Z
  '79caaf5347e6e4a94c8e78a98496fc74020f809ede13f220fab6104c8ded329f',

  // ISRG Root X1 (issued by ISRG Root X1)
  // Expires: 2035-06-04T11:04:38.000Z
  '0b9fa5a59eed715c26c1020c711b4f6ec42d58b0015e14337a39dad301c5afc3',

  // SecureSign Root CA14 (issued by SecureSign Root CA14)
  // Expires: 2045-04-08T07:06:19.000Z
  '581cc15821169694c39c2991b53e93ab945a42b076661774c2ecf38a3323acea',

  // Telia Root CA v2 (issued by Telia Root CA v2)
  // Expires: 2043-11-29T11:55:54.000Z
  'c2b3c31a4a29850aa8f3cf472a1169ff71b416579f6a4482ec7744b83df988ac',

  // BJCA Global Root CA1 (issued by BJCA Global Root CA1)
  // Expires: 2044-12-12T03:16:17.000Z
  'ebc55f21e88d49ede81c0075ab08b3c73b81f0f33e37d7641a1d01b6e602dc9d',

  // TrustAsia TLS RSA Root CA (issued by TrustAsia TLS RSA Root CA)
  // Expires: 2044-05-15T05:41:56.000Z
  '5628872e245fe66148b80badeac9c40f6252e642fa9595aece4b3e8a58b8fd46',

  // GLOBALTRUST 2020 (issued by GLOBALTRUST 2020)
  // Expires: 2040-06-10T00:00:00.000Z
  'fee8af929175687f4638a3fc983db8ecd0e5e2a83e737f3fb77b4c22fcbac0a6',

  // GlobalSign (issued by GlobalSign)
  // Expires: 2034-12-10T00:00:00.000Z
  '682747f8ba621b87cdd3bc295ed5cabce722a1c0c0363d1d68b38928d2787f1e',

  // OU=AC RAIZ FNMT-RCM (issued by OU=AC RAIZ FNMT-RCM)
  // Expires: 2030-01-01T00:00:00.000Z
  '2fc5667a4b9a2678ed6ac6ad25465fcbf6094bfcd9504097c7a8fa47ade5e888',

  // OISTE Server Root RSA G1 (issued by OISTE Server Root RSA G1)
  // Expires: 2048-05-24T14:37:15.000Z
  'b964e141d3a55cae180ea6a1a8d4a297de26f11833c673569d196fb533a98710',

  // GDCA TrustAUTH R5 ROOT (issued by GDCA TrustAUTH R5 ROOT)
  // Expires: 2040-12-31T15:59:59.000Z
  'ceb19411c65052c757f941eb826c96941e4d08d096c7db7e7ea3c4f8c13f1a13',

  // SSL.com TLS RSA Root CA 2022 (issued by SSL.com TLS RSA Root CA 2022)
  // Expires: 2046-08-19T16:34:21.000Z
  '2bcf553a66f570900ddd32ba6dfe1ecc06c9182d662dc1b60e1f7b767c2bdd54',

  // Sectigo Public Server Authentication Root R46 (issued by Sectigo Public Server Authentication Root R46)
  // Expires: 2046-03-21T23:59:59.000Z
  '0e8bb18bbeefb381be21bfc1a206d317298462ad104855f04a0542699708d3d4',

  // CFCA EV ROOT (issued by CFCA EV ROOT)
  // Expires: 2029-12-31T03:07:01.000Z
  'dd5ed1c090f9f448061baa94a6bb11017544e9eefaa20cc714ce6c633f5dc629',

  // TWCA CYBER Root CA (issued by TWCA CYBER Root CA)
  // Expires: 2047-11-22T15:59:59.000Z
  '06600b94c0318bb6967f0c7787cc8a1032a179c4e95e3c5760b32e290f7fec9b',

  // DigiCert Trusted Root G4 (issued by DigiCert Trusted Root G4)
  // Expires: 2038-01-15T12:00:00.000Z
  '59df317bfa9f4f0ab7ca514d7772296aa2c765b87664d08b96e57399e364729c',

  // SwissSign RSA TLS Root CA 2022 - 1 (issued by SwissSign RSA TLS Root CA 2022 - 1)
  // Expires: 2047-06-08T11:08:22.000Z
  'ebc978ae0dd9e5822d6b19652596f620c93d7caefa952191cb050a632ca9005f',

  // NAVER Global Root Certification Authority (issued by NAVER Global Root Certification Authority)
  // Expires: 2037-08-18T23:59:59.000Z
  '786ffa578618c3b9a311175e50816f4dda0605c3869f296ebc5943bf09f4e904',

  // HARICA TLS RSA Root CA 2021 (issued by HARICA TLS RSA Root CA 2021)
  // Expires: 2045-02-13T10:55:37.000Z
  '693c9aa6b245b3b0261637750863eadb6c248a16e52d6f4bc90c86bbf32d7042',

  // TrustAsia Global Root CA G3 (issued by TrustAsia Global Root CA G3)
  // Expires: 2046-05-19T02:10:19.000Z
  '8685ad850f7f56cd16943bcb70b434e7356e1b8bdc613406e2ea8de46092b636',

  // Microsoft RSA Root Certificate Authority 2017 (issued by Microsoft RSA Root Certificate Authority 2017)
  // Expires: 2042-07-18T23:00:23.000Z
  'b2f7298b52bf2c3cac4ddfe72de4d682ac58957595982f2b62301af597c699c5',

  // D-TRUST EV Root CA 2 2023 (issued by D-TRUST EV Root CA 2 2023)
  // Expires: 2038-05-09T09:10:32.000Z
  'e753cdd9f13413c7ca9cda82962f8c0ce5ed13d1657312954af5267eb2cb7c79',

  // D-TRUST BR Root CA 2 2023 (issued by D-TRUST BR Root CA 2 2023)
  // Expires: 2038-05-09T08:56:30.000Z
  'ac76f63a46e761b5acc3259705c920cb7f0563d248d8d180f934af68099a15f9',

  // OU=ePKI Root Certification Authority (issued by OU=ePKI Root Certification Authority)
  // Expires: 2034-12-20T02:31:27.000Z
  '62554c17005543b237215f04268dcd2fd1c470240ad3c8660e25ae2c59630f55',

  // Telekom Security TLS RSA Root 2023 (issued by Telekom Security TLS RSA Root 2023)
  // Expires: 2048-03-27T23:59:59.000Z
  '0e05e9bb23869eb689dc56839dcec475a3ae75fa6b50bc5a4978360cbe673323',

  // TunTrust Root CA (issued by TunTrust Root CA)
  // Expires: 2044-04-26T08:57:56.000Z
  'c942262c0c7c0a95bb152b71c42556ddbe9a04fa8378373550d2b7ce27d952a3',

  // QuoVadis Root CA 2 (issued by QuoVadis Root CA 2)
  // Expires: 2031-11-24T18:23:33.000Z
  '8fd112c3c8370f147d5ccd3a7d865eb8dd540783bac69fc60088e3743ff33378',

  // SwissSign Gold CA - G2 (issued by SwissSign Gold CA - G2)
  // Expires: 2036-10-25T08:30:35.000Z
  '40fcfc28875dccbfebcbdf6cd7433312da63c4efcf3bd7b1b505c22020ae0274',

  // Actalis Authentication Root CA (issued by Actalis Authentication Root CA)
  // Expires: 2030-09-22T11:22:02.000Z
  '25d4913cf587097414d29d26f6c1b1942cd6d64eaf45d0fcf81526adba96d324',

  // Certum Trusted Root CA (issued by Certum Trusted Root CA)
  // Expires: 2043-03-16T12:10:13.000Z
  '681dc482c296c8402c6ebb20e68309a3bc846523ae34b984a84ee697a3312db7',

  // Hongkong Post Root CA 3 (issued by Hongkong Post Root CA 3)
  // Expires: 2042-06-03T02:29:46.000Z
  '2541e53ba5b3b07acbe7097ac4a03e040c11cf7a6d4a67cb213d558b50167a06',

  // Hellenic Academic and Research Institutions RootCA 2015 (issued by Hellenic Academic and Research Institutions RootCA 2015)
  // Expires: 2040-06-30T10:11:21.000Z
  '50cc86ba96db3263c79a43ead07553d9f56659e6907e72d8c026637a1cdc85dc',

  // Autoridad de Certificacion Firmaprofesional CIF A62634068 (issued by Autoridad de Certificacion Firmaprofesional CIF A62634068)
  // Expires: 2036-05-05T15:22:07.000Z
  '3b0d73b4be4a854adc3e51d7ef9fa48aefbb2cdd824d67bdc7d7d09a2abc2d43',

  // Certigna Root CA (issued by Certigna Root CA)
  // Expires: 2033-10-01T08:32:27.000Z
  '8e8046ec4cac015a507ce0d2d0154a4b40e8e42b3165cfa546571435112d17e5',

  // QuoVadis Root CA 3 (issued by QuoVadis Root CA 3)
  // Expires: 2031-11-24T19:06:44.000Z
  '0c7acaa710226720bbc940349ee2e6148652a89dbf406a232c895f6dc78ebb9a',

  // ACCVRAIZ1 (issued by ACCVRAIZ1)
  // Expires: 2030-12-31T09:37:37.000Z
  '05570ae6eb0fceb4210e6db79486b7094caf200401e149b6677441b5f25e449b',
];
